server:
  port: 8085
  compression:
    enabled: true
  servlet:
    session:
      timeout: PT30M
      cookie:
        max-age: PT720H
  undertow:
    direct-buffers: true
    buffer-size: 10240
    worker-threads: 50
    io-threads: 50
    max-http-post-size: 102400
    accesslog:
      dir: ${user.dir}
      enabled: true
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  thymeleaf:
    cache: false
    enable-spring-el-compiler: false
  #      prefix: classpath:/
  #      suffix: .html
  datasource:
    name: my
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: root
      #配置初始化大小/最小/最大
      #          initial-size: 1
      #          min-idle: 1
      #          max-active: 20
      #获取连接等待超时时间
      #          max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      #          time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      #          min-evictable-idle-time-millis: 300000
      #          validation-query: SELECT 'x'
      #          test-while-idle: true
      #          test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#          pool-prepared-statements: false
#          max-pool-prepared-statement-per-connection-size: 20
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.jwt.model  # 注意：对应实体类的路径

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

#mapper
#mappers 多个接口时逗号隔开
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
